### ISSUE TITLE
runbot_travis2docker: does not seem to work on OCA runbot

### ISSUE THREAD

**Issue by gurneyalex** [OCA/runbot-addons#105]
I probably got some configuration wrong. 

I'm using docker 1.6.2 (from jessie-backports), the user running odoo is a member of the docker group (but odoo is not running inside docker). 

Test repository is https://runbot.odoo-community.org/runbot/repo/github-com-vauxoo-dev-runbot-branch-remote-name-grp-feature2-232

Setup:

![screenshot from 2016-11-07 17-39-14](https://cloud.githubusercontent.com/assets/2032807/20066293/58210b50-a511-11e6-889a-22891b8fccd0.png)
I get empty builds or skipped builds, `docker ps` says nothing, and `docker images` is also empty. 

Weird line in the logs:
```
2016-11-07 16:23:12,856 4580 INFO openerp-oca-runbot openerp.addons.runbot_travis2docker.models.runbot_build: Dockerfile without TESTS=1 env. Skipping builds [3271674]
```

**Comment by gurneyalex** [comment]
@moylop260 your feedback is very welcome on this. Thanks for your help.

**Comment by moylop260** [comment]
What is your `travisfile2dockerfile --version`?

**Comment by moylop260** [comment]
`travisfile2dockerfile --version`

**Comment by lasley** [comment]
The Travis file needs to be upgraded to the new version. This error is saying there is no "TESTS=1" in the matrix, which is defaulted so doesn't hurt Travis. 

Happens all the time on our instance, which is why you see me submitting new Travis files quite often. You can see the transition on our [web](https://runbot.laslabs.io/runbot/repo/git-github-com-laslabs-web-git-54) repo. Skipped are all before merge of OCA/web#447 or OCA/web#448

Although @moylop260 comment maybe alludes to this being fixed in a newer T2D version?

**Comment by moylop260** [comment]
@gurneyalex 
I'm using the following `runbot.repo` configuration:
![docker](https://cloud.githubusercontent.com/assets/6644187/20067819/351772aa-a4dc-11e6-8317-36ca42c94a87.png)

It's building here:
http://runbot.vauxoo.com/runbot/repo/https-github-com-vauxoo-dev-runbot-branch-remote-name-grp-feature2-git-90

I don't see the url in the image of your first comment but could change it by:
https://github.com/vauxoo-dev/runbot_branch_remote_name_grp_feature2.git

NOTE: The docker version is too old this could get new errors by old bug but Its is other matter.

**Comment by moylop260** [comment]
@lasley 
Thanks for the information.

For this case we are using a `.travis.yml` file upgraded:

https://github.com/vauxoo-dev/runbot_branch_remote_name_grp_feature2/blob/ac681dcb4cfcbb8df9c26ed8cadf8e4c837f21be/.travis.yml#L21-L27

**Comment by lasley** [comment]
Yup that Travis should definitely not be exhibiting this issue 😦

**Comment by gurneyalex** [comment]
@moylop260 

```
$ bin/travisfile2dockerfile --version
travisfile2dockerfile 3.0.8
```

**Comment by moylop260** [comment]
@gurneyalex 
Could you share me a screenshot of runbot.repo record but without edition mode, please? (To show the full url)

**Comment by moylop260** [comment]
@gurneyalex 
The repository installed  are:
- https://github.com/gurneyalex/runbot-addons/tree/9.0-OCA-installation
- https://github.com/gurneyalex/odoo-extra/tree/OCA-runbot

Right?

**Comment by gurneyalex** [comment]
@moylop260 I think the problem comes from https://github.com/gurneyalex/odoo-extra/commit/92b578a4a3bfca8f23dc474357938be7f43fccd6 which is installed on our instance : the screenshot shows the configured URL (without the https:// prefix which is added by that patch, and your addon expects a full URL.

**Comment by moylop260** [comment]
@gurneyalex Thanks for the information
Fix https://github.com/OCA/runbot-addons/pull/106

**Comment by gurneyalex** [comment]
@moylop260 things seem to be better, cf. 

https://runbot.odoo-community.org/runbot/repo/github-com-vauxoo-dev-runbot-branch-remote-name-grp-feature2-232

**Comment by gurneyalex** [comment]
@moylop260 at lease 1 build worked. Are the failures on the other branches expected ?

**Comment by moylop260** [comment]
Yeah, we have currently the following issue
 https://github.com/OCA/maintainer-quality-tools/pull/384 (Installing just base show that error)

Showing in travis too the same error:
[travis-build-OCA/maintainer-quality-tools#384](https://travis-ci.org/OCA/maintainer-quality-tools/jobs/175720269#L277-L283)

Then it is not a runbot or travis2docker error. It is a MQT expected fail.
![borrar](https://cloud.githubusercontent.com/assets/6644187/20269044/25ac0158-aa47-11e6-9c9d-57b8983229a0.png)

IMHO we are ready (We don't have real projects installing just base)

**Comment by moylop260** [comment]
We could use a "technical" real repository like as [server-tools](https://github.com/oca/server-tools)

I'm testing it from custom instance using all the patches and It is working fine:

![server-tools](https://cloud.githubusercontent.com/assets/6644187/20270360/5e0da29a-aa4c-11e6-9bca-b2a7702d386f.png)

**Comment by gurneyalex** [comment]
Yesterday I enabled docker builds for
- rma (5 instances running on docker at the moment)
- server-tools (7 instances)

**Comment by gurneyalex** [comment]
I just enabled
- account-financial-tools
- web
- website

For now all of them have the tests disabled (same for rma and server-tools). 

cc @moylop260 @lasley

**Comment by lasley** [comment]
Hmmm looks like the new version isn't appending the log to DB. I admittedly haven't updated my Runbot since before the code sprint, so I haven't functionally tested our improvements outside of local. I'll update today and see what's wrong.

**Comment by lasley** [comment]
Fix is in #107 - seems my PEP8ing after test and before PR ended up changing the end result of the `.format`. My bad on that, I was going a lot of directions during the code sprint

**Comment by moylop260** [comment]
To see the logs we need a `log.warning` or a `log.error` into of a build.
But I don't found the first one with this log.

How are you checking this issue?

**Comment by moylop260** [comment]
I found a warning in a runbot build but is not enabled for docker.
The branch 8.0 of https://runbot.odoo-community.org/runbot/repo/github-com-oca-l10n-switzerland-125

@gurneyalex 
Could you help us to enable it in this project in order to confirm a issue with the logs?

**Comment by gurneyalex** [comment]
added
- carrier-delivery
- product-*
- stock-*
- community-data
- l10n-switzeland (cc @moylop260 I triggered a rebuild of the 8.0 branch)

**Comment by moylop260** [comment]
I saw in stock-\* project the following error (and fix): https://github.com/OCA/maintainer-quality-tools/pull/386

**Comment by moylop260** [comment]
I saw in l10n-switzerland project the following error (and fix): https://github.com/Vauxoo/docker-odoo-image/commit/3eaae030aa04f81a22ee0dbdd54b50f414d7dab9

<s>
(This change require run the following command in the oca server: `docker pull vauxoo/odoo-80-image-shippable-auto`)

TODO: Use the parameter `--pull` from runbot-addons to auto-pull the big image in each change.
</s>

**Comment by moylop260** [comment]
> TODO: Use the parameter --pull from runbot-addons to auto-pull the big image in each change.

Fixed from https://github.com/OCA/runbot-addons/pull/109

**Comment by lasley** [comment]
Gotta love the edge cases that crop up when launching at scale 😉

**Comment by lasley** [comment]
@gurneyalex - We made some changes that will resolve the issues we've been seeing. _Edit: it may only be [this issue](https://github.com/OCA/website/pull/284#issuecomment-260777911) now that I think about it_

Would you mind doing a `pip install git+https://github.com/Vauxoo/travis2docker.git` to grab the new version of T2D that includes https://github.com/Vauxoo/travis2docker/pull/77? 

We'll also need to update the runbot addon to the new version merged in #109.

**Comment by gurneyalex** [comment]
I'm sorry I can't today. I'll try hard tomorrow.

**Comment by gurneyalex** [comment]
@lasley @moylop260 I've just updated the runbot as requested

**Comment by moylop260** [comment]
Thank you
T2d upgrade is required too
pip install git+https://github.com/Vauxoo/travis2docker.git
Please

**Comment by gurneyalex** [comment]
@moylop260 I did this. Running 99680477d329aee2e54b9cf512531479cd118920 (which is on 3.0.8).

**Comment by gurneyalex** [comment]
maybe I'm catching an outdated version. Can you make a 3.0.8 release and publish it on pypi ? It's way easier for me due to the way the runbot is deployed to use published documented versions rather than github heads.

**Comment by moylop260** [comment]
I'll do it
Thank you

**Comment by moylop260** [comment]
Someone is wrong
All builds are skipping
I'll check it

**Comment by moylop260** [comment]
With the following environment:
- runbot-addons
 
```bash
~/runbot-addons (9.0-OCA-installation)$ git log -r -2
commit 33e5a2abb43cbd24b738d79d18964de7c3f17997
Merge: 251dc63 092e6f8
Author: Alexandre Fayolle <alexandre.fayolle@camptocamp.com>
Date:   Wed Nov 23 15:01:53 2016 +0100

    Merge remote-tracking branch 'origin/9.0' into 9.0-OCA-installation

commit 092e6f889b252f82cc2abd1bfb87f6443a37bf5b
Merge: 8044166 b0a5635
Author: Pedro M. Baeza <pedro.baeza@gmail.com>
Date:   Mon Nov 21 18:30:03 2016 +0100

    Merge pull request #109 from vauxoo-dev/9.0-oca-pull-img-moy

    [REF] runbot_travis2docker: Auto pull image for long-term updates
```

- travis2docker
```bash
pip install --upgrade travis2docker==3.0.9
travisfile2dockerfile --version
travisfile2dockerfile 3.0.9
```

- Rebooting the odoo server.
- Pressing `Rebuild` button of the build https://github.com/vauxoo-dev/runbot_branch_remote_name_grp_feature2/tree/fast-travis


* Result:

It's not skipped
![screen shot 2016-11-23 at 12 15 16 pm](https://cloud.githubusercontent.com/assets/6644187/20573629/57eccba8-b176-11e6-8daf-b445acd93378.png)


Do you have a logger error?

**Comment by moylop260** [comment]
@gurneyalex The `odoo-extra` have the patch of the `https//` applied yet, right? (I don't have other idea)

**Comment by moylop260** [comment]
@gurneyalex Tell me if I can help...

**Comment by gurneyalex** [comment]
I'm sorry I was away yesterday. I just updated the runbot. I'll monitor carefully the builds in the coming hours

**Comment by gurneyalex** [comment]
@moylop260 Things seem to be a bit better. My build on https://github.com/OCA/web/pull/498 was correctly processed.

**Comment by lasley** [comment]
@gurneyalex - I rebuilt all of the website builds that were skipped, and we seem good to go. And in even better news, OCA/website#284 now works so that means the RVM install is working too!

**Comment by moylop260** [comment]
> I saw in stock-\* project the following error (and fix): https://github.com/OCA/maintainer-quality-tools/pull/386

I rebuilt https://runbot.odoo-community.org/runbot/build/3273461 and now is working

> I saw in l10n-switzerland project the following error (and fix): https://github.com/Vauxoo/docker-odoo-image/commit/3eaae030aa04f81a22ee0dbdd54b50f414d7dab9

I rebuilt https://runbot.odoo-community.org/runbot/build/3273217 and now is working
(We have other unrelated error fixed here: https://github.com/OCA/l10n-switzerland/pull/284)

**Comment by moylop260** [comment]
@gurneyalex 
Could we enable travis2docker in other projects?

**Comment by gurneyalex** [comment]
@moylop260 I just enabled travis2docker on *all* projects.
