### ISSUE TITLE
[RFC] runbot_letsencrypt

### ISSUE THREAD

**Issue by hbrunn** [OCA/runbot-addons#128]
latest on https://github.com/OCA/knowledge/pull/137, but I expect a lot more of those in the future, we have the problem that we need a valid SSL certificate for stuff to be testable in the first place. Given the way [rate limiting](https://letsencrypt.org/docs/rate-limits) works for letsencrypt, we can't just request a new certificate for every commit. I'm now in the process to develop a module that does the following. Usually I just release the code, but now I'll not be working on this for a week or two, so let's discuss if this is what we want in the first place:

- configure max letsencrypt requests per week (done)
- show a button to request a cert on the build info if above max is not exhausted (done)
- configure some branches to request a cert automatically (done)
- make the visiblity of the button and the availability of the feature in general depend on membership of group 'Request SSL certificates' (implied by runbo_admin, implies runbot_user, default public_user) (done)
- actually request the certificate (to be done)
    - in a build step before the actual test all is run for branches with automatic ssl certs
    - manually when pressing the button on a running build
- adapt `runbot`'s nginx configuration to pass letsencrypt requests to the main runbot instance (to be done)
- adapt `runbot`'s nginx configuration to point to letsencypt's certs and keys. We want all of the instances to share one cert in order to be allowed to have a hundred of them per week, hence the limit of 99 in the current code
- add `<regex regex="(what)* ever+ you{1,2} feel like" position="replace|after|before|inner" />` to `base_view_inheritance_extension` in order to make the above changes simple and modular

**Comment by hbrunn** [comment]
@dreispt  @gurneyalex @lasley @pedrobaeza this module will be written in the next couple of weekends, any input on further things we need?

**Comment by lasley** [comment]
301 redirect for http to https on secured instances?

**Comment by sbidoul** [comment]
@gurneyalex any opinion on this? Don't we have a wildcard certificate for odoo-community.org that could be used on runbot?

**Comment by lasley** [comment]
@sbidoul IIRC it expired a few months back & we went with a Let's Encrypt solution instead. The cert currently showing for all our resources is Let's Encrypt now.

![image](https://cloud.githubusercontent.com/assets/7397578/26066745/c4af8ed4-394c-11e7-93af-04b087deb833.png)

**Comment by sbidoul** [comment]
@lasley I know but I think the wildcard has been renewed anyway, so it might save a couple of @hbrunn weekends :)

**Comment by lasley** [comment]
Hey @hbrunn - I've been running up against Let's Encrypt's threshold for the past few weeks, and I'm not entirely certain we can use it in our context due to the incredibly low limits (20 per week). I'm thinking I agree with just using a wildcard, assuming that we have it.

@sbidoul - Do you know if we actually have a wildcard for `*.runbot.odoo-community.org`? A wildcard for the third level (`*.odoo-community.org`) won't work on the fourth level IIRC

**Comment by sbidoul** [comment]
@lasley the certificate that was renewed in March 2017 by @jgrandguillaume was for odoo-community.org.

**Comment by lasley** [comment]
Thanks for the info @sbidoul! Btw where did you find that info? 

If it's only for `*.odoo-community.org`, we won't be able to use it on Runbot anyways. We would need one for `*.runbot.odoo-community.org`, or would need to reissue the existing cert with `*.runbot.odoo-community.org` in the SAN

**Comment by elicoidal** [comment]
@lasley agree: it would be easier to have a wildcard *.runbot.odoo-community.org

**Comment by lasley** [comment]
I just grudgingly did this on my own Runbot, which was secured under a Starcom cert issued after 10-21-2016 & was [rendered invalid](https://blog.mozilla.org/security/2016/10/24/distrusting-new-wosign-and-startcom-certificates/).

At this point we're having trouble keeping our production SaaS instances secured with Let's Encrypt, which makes me feel like Runbot is a lost cause until thresholds change or we figure out a way to request them in giant batches.

**Comment by hbrunn** [comment]
well, I still plan to continue working on this, because in some rare events, I'd also like to connect to some instance on one of our private runbot's instances securely.
You'll find the beginnings in https://github.com/hbrunn/runbot-addons/tree/8.0-runbot_letsencrypt/runbot_letsencrypt

Recently, I also stumbled upon https://docs.google.com/forms/d/e/1FAIpQLSfg56b_wLmUN7n-WWhbwReE11YoHXs_fpJyZcEjDaR69Q-kJQ/viewform?c=0&w=1 which might be accepted for the OCA (not for Therp, but we're also not going to need this)

**Comment by hbrunn** [comment]
...if your organization has some bucks to spend, this seems a good idea to me: https://letsencrypt.org//2017/07/06/wildcard-certificates-coming-jan-2018.html

**Comment by lasley** [comment]
LasLabs just tossed in the pot & OCA is talking about it internally 👍

**Comment by moylop260** [comment]
Is this issue still valid @hbrunn ?

**Comment by hbrunn** [comment]
no, my colleague is hacking [wildcard support into the letsencrypt addon](https://github.com/OCA/server-tools/pull/1194)
thanks for the reminder
