### ISSUE TITLE
Weblate from runbot_travis2docker is used for new weblate release?

### ISSUE THREAD

**Issue by moylop260** [OCA/runbot-addons#162]
Currently weblate is based from .pot
Then too many code was deprecated.
The question is if we should deprecate the code here too

https://github.com/OCA/runbot-addons/blob/9.0/runbot_travis2docker/models/runbot_repo.py#L34

cc @sbidoul @benwillig

**Comment by sbidoul** [comment]
Yes, runbot is not used for the weblate integration. This code can be removed too.

**Comment by moylop260** [comment]
Fixed from https://github.com/OCA/runbot-addons/pull/166
