### ISSUE TITLE
runbot_travis2docker: the section after_success is not taken into account

### ISSUE THREAD

**Issue by luisg123v** [OCA/runbot-addons#168]
Currently, the section `after_success` of the file `.travis.yml` is not being taken into account when Running tests on Runbot:

https://github.com/OCA/runbot-addons/blob/0208528151cf52ae1ab13bffaa10d0d575475995/runbot_travis2docker/models/runbot_build.py#L145

IMO, that section should not be skipped, because it truncates the possibility of adding pre-shutdown or clean up steps for Runbot.

**Comment by luisg123v** [comment]
@moylop260 
I noticed  you were the original author of this behavior, introduced on https://github.com/oca/runbot-addons/commit/228ace1d3fe135ce0aabae11297c18e7fb60d261. So I'd like to know, What do you think? Do you agree with me?

**Comment by MiquelRForgeFlow** [comment]
If this issue has been attended, then it can be closed.

**Comment by luisg123v** [comment]
@mreficent  
This issue is waiting for community feedback, I'd like a confirmation before submiting a patch.

**Comment by MiquelRForgeFlow** [comment]
Ah, sorry, I went too fast, and I thought that it was attended.

**Comment by luisg123v** [comment]
Yes, it's wrongly associated to an unrelated commit

**Comment by moylop260** [comment]
After success it used for upload coverage results
For now, runbot is not running test then it is not needed.
Maybe you could review extra scripts parameter from:
 https://github.com/OCA/runbot-addons/pull/179
