### ISSUE TITLE
502 Bad Gateway nginx/1.6.2

### ISSUE THREAD

**Issue by MiquelRForgeFlow** [OCA/runbot-addons#171]
I don't know if it fails because OCA shenanigans or if it's Odoo shenanigans, but sometimes in a PR, when I rebase and push force, when you try to enter in a green Runbot, it shows:

```
502 Bad Gateway
------------------------------------
nginx/1.6.2
```

The problem is that this error can't be repaired by force-rebuild. And neither by just doing some commit changes and doing push force again. If the problem happens in the "n" runbot of the PR, then it will maintain this error in the "n" runbot of the PR, independently of your new commits and changes you do.

I can solve it by adding a new dummy commit, but it's stupid. I don't want to have dummy commits in my PRs.

I had this problem in https://github.com/OCA/contract/pull/170 ([runbot](https://runbot.odoo-community.org/runbot/build/3333766)) and in https://github.com/OCA/account-reconcile/pull/212 ([runbot](https://runbot.odoo-community.org/runbot/build/3333756)).

**Comment by MiquelRForgeFlow** [comment]
@pedrobaeza @hbrunn @moylop260 @gurneyalex

**Comment by moylop260** [comment]
Could you use a “incognito” way from your browser?
I just connected to last runbot build from 
https://github.com/OCA/contract/pull/170 working as well
