### ISSUE TITLE
[RFC][runbot_exclude_warns] Ability to exclude certain warnings in runbot

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/runbot-addons#172]
Sometimes a runbot execution produces warnings while installing python modules using pip that are not really harmful and could be ignored. See for example https://github.com/OCA/ddmrp/pull/17#issuecomment-409593086

The runbot log shows a warning that is not really harmful:
![image](https://user-images.githubusercontent.com/7683926/43576500-cf3f79e4-9649-11e8-99db-7505331958b6.png)

The PR appears as if Runbot is broken:
![image](https://user-images.githubusercontent.com/7683926/43576451-b6de664e-9649-11e8-95ac-eb5913eefe15.png)

We propose a module that would allow you to exclude warnings that contain a certain string, like: "numpy.dtype size changed".

This behaviour would be added here: https://github.com/odoo/runbot/blob/master/runbot/models/build.py#L834

And the strings to exclude could be specific to a repo.

Perhaps it's a crazy idea ¿??

cc @lreficent

**Comment by pedrobaeza** [comment]
You should fix the warning, as it shouldn't happen.

**Comment by JordiBForgeFlow** [comment]
Was fixed in numpy package 2 days ago https://github.com/numpy/numpy/pull/11634, but seems that an older version of numpy is being installed....

**Comment by pedrobaeza** [comment]
Add the new one to the requirements.txt file in root

**Comment by moylop260** [comment]
FYI I just used ssh runbot connection to check numpy issue...

Please, check my comment here:
 - https://github.com/OCA/ddmrp/pull/17#issuecomment-410383000

IMHO this warning is a valid one
Closing since that currently we don't have a real warning to ignore.
