### ISSUE TITLE
Runbot fails

### ISSUE THREAD

**Issue by MiquelRForgeFlow** [OCA/runbot-addons#173]
In PR https://github.com/OCA/partner-contact/pull/615, you may find that runbot fails in last commit. When I check for [full logs](https://runbot.odoo-community.org/runbot/static/build/3335945-615-7d56c2/logs/job_20_test_all.txt), it shows:
```python
Unable to find image 'oca-partner-contact:7d56c21_3' locally
docker: Error response from daemon: repository oca-partner-contact not found: does not exist or no pull access.
See 'docker run --help'.
```
Obviously I tried to rebuild it, but still shows the same problem.

--

**Comment by MiquelRForgeFlow** [comment]
@gurneyalex @moylop260 I hope you can say something about this error 😅

**Comment by moylop260** [comment]
The [full base logs](https://runbot1.odoo-community.org/runbot/static/build/3335945-615-7d56c2/logs/job_10_test_base.txt)
`Error response from daemon: Untar error on re-exec cmd: fork/exec /proc/self/exe: resource temporarily unavailable`
I don't know if the hard disk is full or it was a isolated error.

**Comment by pedrobaeza** [comment]
@gurneyalex said that PIDs were exhaust and he raised the number of them, but maybe it's not enough and a cleanup should be done. The problem came from an incorrect repository name that was consuming processes each time.

**Comment by gurneyalex** [comment]
I'm giving it a look

**Comment by gurneyalex** [comment]
I also raised the number of threads in sysctl.conf. 

Monitoring for new failures.

**Comment by MiquelRForgeFlow** [comment]
please, apply same magic to fix the runbot in https://github.com/OCA/contract/pull/170

**Comment by moylop260** [comment]
I just press the button: rebuild
let's see if it is fixed
-- 
Moisés López Calderón
Mobile: (+521) 477-752-22-30
Twitter: @moylop260
hangout: moylop260@vauxoo.com
http://www.vauxoo.com - Odoo Gold Partner
Twitter: @vauxoo

**Comment by gurneyalex** [comment]
closed.
