### ISSUE TITLE
[11.0] Problems with 'lock'

### ISSUE THREAD

**Issue by luistriana28** [OCA/runbot-addons#192]
File "/home/odoo/runbot-addons/runbot_buildout/models/runbot_build.py", line 17, in <module>
    from odoo.addons.runbot.common import lock, grep
ImportError: cannot import name 'lock'

I have been trying to satisfied this requirement about 'lock', even with sudo apt-get python-lockfile or sudo pip install lockfile but there is no good answer.

My odoo.conf I put the runbot module in first line

addons_path=
    /home/odoo/runbot,
    /home/odoo/odoo/addons,
    /home/odoo/runbot-addons

This is in a new clean server with ubuntu 18.04

Regards

**Comment by moylop260** [comment]
You are using dockerized odoo/runbot and it is not compatible with this project anymore.

You need use pre-docker release:
 - https://github.com/odoo/runbot/releases/tag/pre-docker 

You can see runbot.common.lock method
https://github.com/odoo/runbot/blob/549452f12dafd5b74ef5a0cb924da1c3f0edc964/runbot/common.py#L37
