### ISSUE TITLE
Runbot fork or runbot patch?

### ISSUE THREAD

**Issue by moylop260** [OCA/runbot-addons#3]
I want define a question more that a issue.

@bwrsandman,
This project not is a fork of odoo/odoo-extra
We have new modules for check PR of dependencies, make a custom build, pylint test...
However, it will need changes in runbot core.

I want to ask:
Do we overwrite original function with copy and paste in a new module? (ugly decision)
Do we make a fork with this new changes in ___ repo? (+1)
Do we make a module with a patch diff file? (bad decision too)

What do you think about this?

**Comment by bwrsandman** [comment]
We make modules which overwrite functions.
In the functions, we try to re-use original behaviour as much as possible by calling `super`.
If a function is completely reimplemented, don't call super and use new code.

If a function in the original module badly needs to be refactored, small patches can be proposed to odoo-extra.

Not much copy-pasting is required.

**Comment by moylop260** [comment]
Ok I got it.
I will make many patch as I need it.
We will wait by @odony
https://github.com/odoo/odoo-extra/pull/33
https://github.com/odoo/odoo-extra/pull/32
Can you help me to comment it?
TODO: More fixes

However, if our need a function reimplemented without super, this should make a conflict with other ones.
But I will send you case a case a comment here.
