### ISSUE TITLE
Runbot invalidates PRs because of warnings

### ISSUE THREAD

**Issue by StefanRijnhart** [OCA/runbot-addons#34]
The Runbot feedback to PRs on GitHub now invalidates code that passes on Travis. Am I right in thinking that this is not the goal of the Runbot?

While warnings sometimes can and should be fixed (e.g. https://github.com/OCA/account-financial-tools/pull/194), there are other cases that are more dubious (e.g. https://github.com/OCA/hr/pull/93#issuecomment-94498687)

What do you think of ignoring warnings for the Runbot judgement?

cc @gurneyalex, @bwrsandman

**Comment by bwrsandman** [comment]
This is pretty easy, all that's needed is to patch the [section](https://github.com/odoo/odoo-extra/blob/44733671fd8f0fd707a0dc72ee26c6d8d80be76b/runbot/runbot.py#L803) which does the return code.

**Comment by StefanRijnhart** [comment]
So you agree with the principle?

Probably arbitrary, but it looks like we can keep the 'warn' result if that is useful and instead change the Github verdict for builds with such a result here: https://github.com/odoo/odoo-extra/blob/44733671fd8f0fd707a0dc72ee26c6d8d80be76b/runbot/runbot.py#L747

**Comment by bwrsandman** [comment]
That works too. Keeping warning could be useful, but Odoo marks so many things as warnings such as missing po files or missing rights.

These should be picked up by travis, though. We should only be interested in the running aspect since we skip tests.

**Comment by StefanRijnhart** [comment]
What branch do I propose to? Is there a specific OCA branch that the OCA
runbot runs?

Also not looking forward to setting up my own runbot just to test this
change...

**Comment by bwrsandman** [comment]
Runbot is from odoo-extra

I recommend using a VM, deactivating the cron and running it manually.

**Comment by gurneyalex** [comment]
Sorry for not reacting earlier on this. 

I would like OCA modules to be warning clean. It previously was not possible because warnings were being triggered by the core. Odoo has fixed this, and I'm in favor of pursuing this. Often warnings are a sign of underlying problems (such as a lack of a database action to fill in a required column). We want to catch theses. 

Let's discuss this during the sprint.

**Comment by gurneyalex** [comment]
@StefanRijnhart the runbot branch which is deployed on the OCA runbot is https://github.com/gurneyalex/odoo-extra/tree/OCA-runbot

**Comment by StefanRijnhart** [comment]
Closing after discussion at code sprint.
