### ISSUE TITLE
Medium contribution: add oca_dependencies.txt support

### ISSUE THREAD

**Issue by bwrsandman** [OCA/runbot-addons#37]
Some of the OCA repos have (oca_dependencies.txt)[https://github.com/OCA/maintainer-quality-tools/blob/master/sample_files/oca_dependencies.txt] files which explicitly state what to branch.

Currently, runbot module dependencies are expressly stated inside the `runbot.repo` object.

We would like to still use the `runbot.repo` dependencies unless a `runbot.branch` contains `oca_dependencies.txt`, in which case, it overrides the dependencies from `runbot.repo`.

This logic is found in the runbot repo in odoo-extra.

**Comment by pedrobaeza** [comment]
Well, I suggest to blend both instead one or the other.

**Comment by bwrsandman** [comment]
I disagree. A lot of v8 repos have less dependencies than v7 ones. Blending both would not bring anything new and would take longer to build.

**Comment by pedrobaeza** [comment]
Yeah, you're right. It's better to take as priority the oca_dependencies.txt file.

**Comment by pedrobaeza** [comment]
Done with the runbot dockerized.
