### ISSUE TITLE
mailcatcher for runbot

### ISSUE THREAD

**Issue by OSguard** [OCA/runbot-addons#42]
http://mailcatcher.me/ or something simular to support to test emails

**Comment by moylop260** [comment]
What about [MailHog](https://github.com/mailhog/MailHog)?

**Comment by moylop260** [comment]
@gurneyalex Is possible creates a MailHog server to catch all the emails and test it?
FYI I think that @ruiztulio could help us

**Comment by gurneyalex** [comment]
I'm not sure how we want to set this up ? I can easily install 1 global mailhog / mailcatcher server  for the OCA and then you can configure the runbot builds to use it for your tests.

I'm concerned that having this configured by default  on all instances will just create a lot of noise on the mail catcher and not be helpful for testing. 

Opinion?

**Comment by moylop260** [comment]
You have a good point...

@ruiztulio what do you think about?

**Comment by gurneyalex** [comment]
@OSguard do you have an opinion on this?

**Comment by ruiztulio** [comment]
@gurneyalex Yes it will, is a lot of mail.

I configured it using iptables in the test instances (those uses a production like database) and as we have them in docker containers it was a little easier to do and we don't have to channge the instance configuration (we do it just in case)

**Comment by gurneyalex** [comment]
I'm :-1:  on the idea of having this set up. Configuring your own catcher and setting up Odoo to run this  in a single runbot instance when you need it is very easy. 

I'm closing. Shout if you disagree
