### ISSUE TITLE
Easy contribution: Add option to see warning as success

### ISSUE THREAD

**Issue by bwrsandman** [OCA/runbot-addons#47]
Runbot status warning (yellow builds) report their status as Failed (red X) on github/gitlab.

Add an option on the repo called success_on_warn (string="Success on Warn", help="Runbot builds with warnings in the log still report success on Pull request")

**Bonus**: Add a global option for this in Settings/Runbot Settings. This option would affect the default of success_on_warn on repos leaving the option to uncheck it for stricter repos.

This can be done as a module or can be proposed to https://github.com/odoo/odoo-extra
It will be accepted quickly here as a module, it might take longer on odoo-extra.

**Comment by moylop260** [comment]
Closing since that is a issue opened a longer time ago without a good welcome
