### ISSUE TITLE
Issue resolving priority when a module is present in multiple addons paths

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/runbot-addons#50]
Hi, @gurneyalex, @bwrsandman,

I ping you as you have more experience with runbot, because I have this problem: in l10n-spain repository, we maintain a more up to date copy of the _l10n_es_ module. This module is also part of the core distribution. We are having these errors on the builds:

https://runbot2.odoo-community.org/runbot/static/build/3111544-8-0-fc08b1/logs/job_20_test_all.txt
https://runbot2.odoo-community.org/runbot/static/build/3111545-7-0-f3e871/logs/job_20_test_all.txt

And the reason for this is that runbot is installing l10n_es from core distribution instead of the l10n-spain repository one. Do you know how can we handle this?

**Comment by pedrobaeza** [comment]
@gurneyalex, do you have time to check this?

**Comment by gurneyalex** [comment]
AFAIR the runbot copies all the addons from the repository to odoo/addons but never overwrites (https://github.com/gurneyalex/odoo-extra/blob/OCA-runbot/runbot/runbot.py#L676) 

So if your addon has the same name as an official addon it will never be used.

**Comment by pedrobaeza** [comment]
Is there a way to solve it? Shouldn't it overwrite?

**Comment by gurneyalex** [comment]
it consciously does not overwrite, the only way of changing this is either:
- rename your addon to something else, and rewrite it
- patch the runbot
- remove l10n-es from OCB

AFAICT l10n-spain is the only localization in OCA which does overwrite a core addon and I'd argue this is not a good practise.

**Comment by pedrobaeza** [comment]
But that's because of it's the same module, but we need the flexibility to add legal changes without waiting the merge in upstream. I'm going to propose it, but it's not possible for now, because we are still changing some taxes and we need the possibility to "test" it on real installations, and this is the only way.

**Comment by nhomar** [comment]
@pedrobaeza What we did for mx and ve is simply change the name, let's say the original is called Spain Localization, I recommend rename yours by l10n_spain_base or something like that.

Make l10n_spain_base dependant of the original one and overwrite xml_id, from time to time make PR to the core, (this modules are pretty straight forward to mantain).

Change the runbot to allow overwrite is a job that is not easy to achieve we need to achiev first the fact of allow several addons-path but AFAICR it is not in the roadmap yet.

Regards.

**Comment by pedrobaeza** [comment]
This is very complicated right now in the middle of the version, but I will find a way to work around it. Thanks for the info.

**Comment by alejandrosantana** [comment]
@pedrobaeza What @nhomar says could be applied in v9 then, seemingly without any problem, isn't it?

**Comment by pedrobaeza** [comment]
Yeah, we can think about it, but the problem is about XML-ID and so on. It's not trivial. Anyway, I'm waiting for the updated XML from @albertgafic and then submit a PR against odoo branch, so that will solve our current problems.
