### ISSUE TITLE
Runbot in v9

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/runbot-addons#69]
Runbot builds for v9 gets this error message

```
UserError: (u'You are trying to install incompatible themes:\n- Bootswatch Theme (To be installed)\n- Default Theme (To be installed)\n\nPlease uninstall your current theme before installing another one.\nWarning: switching themes may significantly alter the look of your current website pages!', None)
```

It seems that there are incompatible modules that cannot be installed together. One option is to list modules to include, but the definition is global or only by branch, so all PRs to OCB will contain the same error. Ideal is to have an exclude list, that blacklisted the modules we don't want to install.

**Comment by pedrobaeza** [comment]
cc @gurneyalex @moylop260

**Comment by moylop260** [comment]
Check if we have next line in production:
https://github.com/odoo/odoo-extra/blob/master/runbot/runbot.py#L713

``` python
 mod_filter = lambda m: (
            m in available_modules and
            (m in explicit_modules or (not m.startswith(('hw_', 'theme_', 'l10n_'))
                                       and m not in blacklist_modules))
        )
```

**Comment by pedrobaeza** [comment]
@gurneyalex, can you check or give me access to the runbot machine?

**Comment by moylop260** [comment]
@pedrobaeza Could we close this issue?

**Comment by pedrobaeza** [comment]
Yes
