### ISSUE TITLE
Runbot not working on l10n-portugal

### ISSUE THREAD

**Issue by dreispt** [OCA/runbot-addons#70]
I'm not sure if this is the right place, but Runbot is not working for the PR localization.
I have no clue on the problem, since when I try opening the logs I get a 404.
Example: https://runbot.odoo-community.org/runbot/build/3135337 (for PR https://github.com/OCA/l10n-portugal/pull/11)

Can someone help?

**Comment by dreispt** [comment]
Ping!

**Comment by moylop260** [comment]
I opened your runbot link but I saw a `502 Bad Gateway` error.
Are there problems with the server?

**Comment by max3903** [comment]
Runbot is back on line and building.

**Comment by max3903** [comment]
and updating the PR.

**Comment by max3903** [comment]
@dreispt FYI, the right place would be to send an email to support@odoo-community.org. Thanks!

**Comment by dreispt** [comment]
OK, thanks!
