### ISSUE TITLE
Runbot V9 links - Page not found

### ISSUE THREAD

**Issue by yvaucher** [OCA/runbot-addons#85]
With the "Try it" button, it leads to a page not found.

For example a 9.0 link doesn't work
https://runbot.odoo-community.org/runbot/140/9.0

While a 8.0 link is fine:
https://runbot.odoo-community.org/runbot/140/8.0

9.0 runbot build is present:
https://runbot.odoo-community.org/runbot/repo/github-com-oca-project-140
http://3146047-9-0-00eb00.runbot1.odoo-community.org/web/login

**Comment by yvaucher** [comment]
Not sure it is the right place to report this.

@gurneyalex any idea ?

**Comment by gurneyalex** [comment]
Fixed on our instance. 

see https://github.com/odoo/odoo-extra/pull/104 for more information.
