### ISSUE TITLE
investigate Exception: bus.Bus unavailable on oca runbot

### ISSUE THREAD

**Issue by gurneyalex** [OCA/runbot-addons#9]

**Comment by max3903** [comment]
Odoo runs on 2 ports with gevent (used for the chat):
- on 8069, it gives this error when calling /longpolling but Odoo is running with many workers
- on 8072, it does not give this error message but it only runs with a single worker

Solution
- Disable gevent and the chat module or
- Install a web server in front of Odoo to redirect /longpolling requests to port 8072 and all others to 8069

**Comment by gurneyalex** [comment]
fixed some time ago.
